### ISSUE TITLE
Can't resolve 'pug-plain-loader' in '/opt/node_app'

### ISSUE THREAD

**Issue by LeviSchouten** [yowkah/taggest#2]
When I run the Docker and go to the browser to preview the page I get 

Failed to compile.
    ./src/views/Upload.vue
     Module not found: Error: Can't resolve 'pug-plain-loader' in '/opt/node_app'

Which makes it seem like it doesn't install the package, but it does work if you run it manually by going in to the client folder.

This could for sure be an issue on my end, if so please let me know.

### Reproduction

1. Clone the repo
2. Run ```docker-compose up```
3. When finished either view the page on your ```http://localhost/```  or run ```docker-compose logs client``` to view the logs

**Comment by yowkah** [comment]
please run the `docker-compose up -d --build` command to make sure the client rebuilds itself.
It looks like the pug-plain-loader isn't available in your client container because it wasn't rebuild after the change to dependencies.
